version: '3'
services:
  
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - /lib/postgres/postgres-data:/var/lib/postgresql/data
      - ../db:/docker-entrypoint-initdb.d/  
    env_file: 
      - .env
    
  backend:
    restart: always
    depends_on:
      - postgres
    build: fiano
    ports: 
      - "8000:8000"
    command: python fiano/manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/src
    env_file: 
      - .env
  
  frontend:
    restart: always
    depends_on:
      - backend
    build: fiano-front
    ports: 
      - "3000:3000"
    command: npm run dev 
    volumes: 
      - ./fiano-front:/src
    env_file: 
      - .env
