# Generated by Django 3.1.6 on 2021-02-12 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64, null=True)),
                ('project_status', models.CharField(max_length=64, null=True)),
                ('timeline_start_date', models.DateField(null=True)),
                ('timeline_end_date', models.DateField(null=True)),
                ('actual_start_date', models.DateField(null=True)),
                ('actual_end_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDeliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=64, null=True)),
                ('item', models.CharField(max_length=64, null=True)),
                ('subitem', models.CharField(max_length=64, null=True)),
                ('deliverable_status', models.CharField(max_length=64, null=True)),
                ('price', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('unit', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=64, null=True)),
                ('worker_type', models.CharField(max_length=64, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('salary', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDeliverableSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(max_length=64, null=True)),
                ('timeline_start_date', models.DateField(null=True)),
                ('timeline_end_date', models.DateField(null=True)),
                ('actual_start_date', models.DateField(null=True)),
                ('actual_end_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('project_deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectdeliverable')),
            ],
        ),
        migrations.AddField(
            model_name='projectdeliverable',
            name='workers',
            field=models.ManyToManyField(to='project.Worker'),
        ),
    ]
