# Generated by Django 3.1.6 on 2021-02-12 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210212_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 12, 18, 28, 0, 941333)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2021, 2, 12, 18, 28, 9, 870820)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectdeliverable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 12, 18, 28, 22, 7285)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectdeliverable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2021, 2, 12, 18, 28, 26, 81005)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectdeliverableschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 12, 18, 28, 28, 307245)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectdeliverableschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2021, 2, 12, 18, 28, 30, 431387)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 12, 18, 28, 32, 602154)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2021, 2, 12, 18, 28, 33, 930519)),
            preserve_default=False,
        ),
    ]
