# Generated by Django 3.1.6 on 2021-02-13 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210213_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdeliverableschedule',
            name='project_deliverable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='project.projectdeliverable'),
        ),
    ]
