# Generated by Django 3.1.6 on 2021-02-16 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20210216_0346'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectdeliverableschedule',
            unique_together={('project_deliverable', 'schedule_type')},
        ),
    ]
